#! /bin/sh
### BEGIN INIT INFO
# Provides:          flash_idle_on_boot
# Required-Start:    $local_fs $time $named
# Required-Stop:     $local_fs $time $named
# Default-Start:
# Default-Stop:
# Short-Description: Flash idle firmware on node boot
### END INIT INFO

PATH=/bin:/usr/bin:/usr/local/bin

NAME=flash_idle
FIRMWARE="/usr/lib/open-a8/idle_a8.elf"
FW_ARDUINO="/usr/lib/open-a8/idle_atmega2560.elf"

# Flash an idle flash for arduino nodes
# Test arduino present and has arduino tty
if { which avrdude && ls /dev/ttyACM* ; }> /dev/null 2>&1
then
    for arduino in /dev/ttyACM*
    do
        avrdude -p atmega2560 -P ${arduino} -c wiring -b 115200 -D -U ${FW_ARDUINO}
    done
fi


# flash A8-M3 node with an idle firmware
/usr/bin/flash_a8_m3 $FIRMWARE
exit $?
