#!/bin/bash

FILE=$(readlink -f "$0")
CFG_FOLDER="/etc/iotlab-flash-scripts"

if [ $# != 1 ]
then
    echo "Usage: $0 <firmware_path>" >&2
    exit 1
fi

openocd -f "${CFG_FOLDER}/iot-lab-m3.cfg" \
	-f "target/stm32f1x.cfg" \
	-c "init" \
	-c "targets" \
	-c "reset halt" \
	-c "reset init" \
	-c "flash write_image erase $1" \
	-c "verify_image $1" \
	-c "reset run"\
	-c "shutdown"
ret=$?
echo "Return Value: $ret"
exit $ret
