#!/bin/bash

FILE=$(readlink -f "$0")
CFG_FOLDER="/etc/iotlab-flash-scripts"

openocd -f "${CFG_FOLDER}/iot-lab-a8-m3.cfg" \
	-f "target/stm32f1x.cfg" \
	-c "init" \
	-c "targets" \
	-c "reset run"\
	-c "shutdown"
ret=$?
echo "Return Value: $ret"
exit $ret
