#! /bin/sh
### BEGIN INIT INFO
# Provides:          flash_idle_on_boot
# Required-Start:    $local_fs $time $named
# Required-Stop:     $local_fs $time $named
# Default-Start:
# Default-Stop:
# Short-Description: Flash idle firmware on linux open node boot
### END INIT INFO

PATH=/bin:/usr/bin:/usr/local/bin
NAME=flash_idle

# flash open node with an idle firmware
FW=idle /usr/bin/iotlab_flash
exit $?
