#! /bin/sh
### BEGIN INIT INFO
# Provides:          serial_redirection
# Required-Start:    $local_fs $time $network $named
# Required-Stop:     $local_fs $time $network $named
# Default-Start:
# Default-Stop:
# Short-Description: Start/stop serial_redirection
# Description: The serial_redirection init script will start/stop socat to
#              redirect serial port to a tcp socket on port 20000
### END INIT INFO

NAME=serial_redirection
DAEMON=/usr/bin/${NAME}
PIDFILE=/var/run/${NAME}.pid

PATH=/bin:/usr/bin:/sbin:/usr/sbin

. /etc/init.d/functions

[ -x $DAEMON ] || exit 0

start_redirection() {
    start-stop-daemon --start \
        --pidfile ${PIDFILE} \
        --background --make-pidfile \
        --exec $DAEMON
}

stop_redirection() {
    start-stop-daemon --stop --pidfile ${PIDFILE}
    rm -f ${PIDFILE}
}

start () {
    echo -n "Starting ${NAME}: "
    start_redirection
    echo $?
    return $?
}

stop () {
    echo -n "Stopping ${NAME}: "
    for PIDFILE in `ls ${PIDFILE} 2> /dev/null`; do
        NAME=`echo $PIDFILE | cut -c16-`
        NAME=${NAME%%.pid}
        stop_redirection
    done
    echo $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status $DAEMON
        exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
        exit 3
        ;;
esac

exit 0
