name: Dunfell Yocto images

on:
  push:
    branches:
    - master
    tags:
      - '*'
  pull_request:
    branches:
    - master

jobs:
  build_images:
    name: Build Yocto images
    runs-on: self-hosted
    timeout-minutes: 720
    strategy:
      matrix:
        target: [a8, rpi2, rpi3, rpi4]
      fail-fast: false
    env:
      BUILD_IN_DOCKER: 1
      BUILD_DOWNLOAD_DIR: /home/ci
      DISTRO_RELEASE: dunfell
    steps:
      - name: Check out install-lib repo
        uses: actions/checkout@v2
        with:
          repository: iot-lab/iot-lab-dev
          token: ${{ secrets.IOTLAB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          path: ./parts/iot-lab-yocto
      - name: Build images
        run: |
          make TARGET=${{ matrix.target }} build-and-upload-images
      - name: Cleanup images
        run: |
          make TARGET=${{ matrix.target }} clean-images
