name: A8 Dunfell Yocto images

on:
  push:
    branches:
    - master
    tags:
      - '*'
  pull_request:
    branches:
    - master

jobs:
  push_to_registry:
    name: Build images
    runs-on: iot-lab-debian-10-1 
    steps:
      - name: Check out install-lib repo
        uses: actions/checkout@v2
        with:
          name: iot-lab/iot-lab-dev
          token: ${{ secrets.IOTLAB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          path: ./parts/iot-lab-yocto
